Dz
GorshkovNI/dzReact pull request #1
Opened 2022-10-24 18:49 UTC by GorshkovNI

Привет
Посмотри, пожалуйста, дз
- [ ] Минимум должны быть общие компоненты Input, Button, Icon
  - [ ] Фильтры открываются, закрываются
  - [ ] Иконка загрузка пока что просто статичная
  - [ ] Кнопка светлая тема тоже просто статичная

2022-10-29 14:07 UTC, Muslik requested changes
Разобрали на уроке

2022-11-01 01:08 UTC, Muslik requested changes
Будет видео

2022-11-08 12:11 UTC, GorshkovNI commented
Посмотри, пожалуйста

2022-11-10 15:54 UTC, Muslik commented
<img width="277" alt="Screenshot 2022-11-10 at 18 53 25" src="https://user-images.githubusercontent.com/15676404/201142920-21d34171-93ec-4d83-a8e7-978c57192181.png">
Кнопки меньше должны быть, шрифт меньше должен быть. По умолчанию светлая тема

2022-11-10 16:06 UTC, Muslik requested changes
Кнопка, размеры в дропдауне с темой и инпут. Есть несколько замечаний.

2022-11-10 16:06 UTC, Muslik commented on src/shared/Input/Input.jsx
> +          <button className={styles.buttonAction} onClick={props.onClick}>
Как по использованию Input-а мне нужно понять что onClick отвечает за какую то кнопочку в конце.

Кнопочек не может быть разное количество. Может быть одна конкретная - кнопка сброса.
Поэтому nameIcon тут не нужен. И onClick превращается в onReset

2022-11-10 16:06 UTC, Muslik commented on src/shared/Input/Input.jsx
> +        {disabled && <Icon name={nameIcon} className={styles.IconDisabled} />}
Тут конкретная иконка с замочком. Она не должна меняться

2022-11-10 16:06 UTC, Muslik commented on src/shared/Input/Input.jsx
> +        {isSelect&& (
Передавайте просто REactNode: prefix

И Инпут не будет знать что там:

```
<Input prefix={<Icon name="arrow" />} />
```

И теперь ваш инпут может работать и с dropdown-ом и с чем то еще

2022-11-10 16:06 UTC, Muslik commented on src/shared/Input/Input.jsx
> +  disabled: 'disabled',
тут disabled уже не нужен.

2022-11-10 16:06 UTC, Muslik commented on src/shared/Input/Input.jsx
> +            <Icon name={nameIcon} className={styles.actionIcon} />
Вот как выглядит ваш инпут в состоянии disabled. Там должно быть иконка замочка. И инпут другого цвета

<img width="464" alt="Screenshot 2022-11-10 at 19 05 20" src="https://user-images.githubusercontent.com/15676404/201146266-3762e17a-baab-4a03-ae9e-e8adaf575076.png">

2022-11-10 16:07 UTC, Muslik commented
Кнопка фильтров должна быть синей когда фильтры открыты

2022-11-10 17:14 UTC, GorshkovNI commented on src/shared/Input/Input.jsx
> +          <button className={styles.buttonAction} onClick={props.onClick}>
Я использую еще эту кнопку для открытия закрытия selector с dropdown.

Соответственно, nameIcon я использую для передачи либо крестика, либо стрелочки вниз, в зависимости от места использования.  И получается, что onClick так же в одном случае служит для открытия закрытия dropdown, в другом для обнуления стейта.

Убрал из кода сейчас полностью кусок с isSelected, был лишним

2022-11-12 07:57 UTC, GorshkovNI commented
поправил

2022-11-17 17:56 UTC, Muslik approved these changes
Есть замечания, будет видео

2022-11-20 12:51 UTC, merged