Table
GorshkovNI/dzReact pull request #2
Opened 2022-11-08 10:17 UTC by GorshkovNI

Привет. Посмотри, пожалуйста

## 3. Собрать таблицу на mocks
  - [] Минимум должны быть общие компоненты: Table, TableHeader, TableFooter, TableBody, TableRow, TableCell, TableHeaderCell, Checkbox
  - [] В таблице есть 100 записей ([Можно сгенерировать](https://json-generator.com/)). Данные лежат в отдельном файле в константе.
  - [] Body у таблицы корректно скроллится. Если у таблицы только один ряд, то футер никуда не уезжает а также корректно вытягивается на всю страницу

2022-11-10 16:16 UTC, Muslik requested changes
Table и все ее дочерние компоненты должны быть в папке shared.

Таблица должна вытягиваться на всю высоту.

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableHeader/TableHeader.jsx
> +      <div className={styles.cells}>{children}</div>
Зачем эта лишняя обертка. Дайте классы контейнеру напрямую

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableBody/TableRow/TableRow.jsx
> +      <div className={styles.cells}>{children}</div>
Опять лишняя обертка

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableBody/TableBodyCell/TableBodyCell.jsx
> +        {checkbox && <CheckBox onClick={onClick} />}
Не нужно зашивать это сюда. TableBodyCell -> TableCell. И тут компонент будет просто children принимать.
```javascript
<TableRow>
  <TableCell>
    <Checkbox />
  </TableCell>
</TableRow>
```

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableBody/TableBody.jsx
> +    <div className={tableBodyClassName} style={{ height: 40 * count }}>
Не должно быть этого style

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/Table.jsx
> +export const Table = () => {
Общего компонента Table я не увидел.

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableFooter/TableFooter.jsx
> +export const TableFooter = ({
Общего компонент TableFooter я не увидел

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/TableHeaderCell/TableHeaderCell.jsx
> +        {checkbox && <CheckBox />}
Не нужно зашивать сюда checkbox

2022-11-10 16:16 UTC, Muslik commented on src/modules/Table/Table.module.css
> +.headerCell:nth-child(3){
Модификаторы задавайте. Завтра два столбика поменяются местами и ваша верстка уедет

2022-11-10 16:18 UTC, Muslik commented
<img width="313" alt="Screenshot 2022-11-10 at 19 18 20" src="https://user-images.githubusercontent.com/15676404/201149479-6b3665a5-65a7-4613-898c-285e0c4a94a9.png">
Иконка должна быть серой

2022-11-12 12:32 UTC, GorshkovNI commented
Переделал

2022-11-16 17:48 UTC, GorshkovNI commented
> 
![Снимок экрана 2022-11-16 224634](https://user-images.githubusercontent.com/98645018/202254931-822bce53-8288-4dc3-8787-eb87716ecff9.jpg)
В макете только внутренний отрезок серый, не понял как сделать только его

2022-11-17 17:55 UTC, Muslik requested changes
Будет видео

2022-11-22 23:45 UTC, Muslik approved these changes

2022-12-03 11:37 UTC, merged